### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by Mytheiw** [cjyaddone/ChatWaifu#18]
Traceback (most recent call last):
  File "C:\Users\Aqil\ChatWaifu\ChatWaifuVoice.py", line 380, in <module>
    resp = api.send_message(voice_input_enjp())
  File "C:\Users\Aqil\miniconda3\envs\chatWaifu\lib\site-packages\pyChatGPT\pyChatGPT.py", line 460, in send_message
    conversation_id = matches.group()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Aionstn** [comment]
The problem is caused by pychatgtp, we need to change the api to call openai, I have a workaround and will share it with the authors

**Comment by MuBai-He** [comment]
Thx bro

**Comment by Mytheiw** [comment]
> The problem is caused by pychatgtp, we need to change the api to call openai, I have a workaround and will share it with the authors

Do you also have problems converting 'voice to text', so what I say isn't the same as the results from the 'voice to text' voice change generator. can you find a solution?
