### ISSUE TITLE
报错，大佬求教

### ISSUE THREAD

**Issue by huiyuezang** [cjyaddone/ChatWaifu#19]
输入token之后出现了这段报错 
Traceback (most recent call last):
  File "D:\ChatWaifu\ChatWaifuJPVoiceJP.py", line 419, in <module>
    api = ChatGPT(session_token)
  File "C:\Users\0\AppData\Local\Programs\Python\Python310\lib\site-packages\pyChatGPT\pyChatGPT.py", line 126, in __init__
    self.__init_browser()
  File "C:\Users\0\AppData\Local\Programs\Python\Python310\lib\site-packages\pyChatGPT\pyChatGPT.py", line 223, in __init_browser
    self.__ensure_cf()
  File "C:\Users\0\AppData\Local\Programs\Python\Python310\lib\site-packages\pyChatGPT\pyChatGPT.py", line 268, in __ensure_cf
    raise ValueError('Invalid session token')
ValueError: Invalid session token
为啥我的token是https%3A%2F%2Fchat.openai.com这种格式  是不是这个token没获取正确的原因？

**Comment by MuBai-He** [comment]
获取的登陆token有问题，重新查看教程

**Comment by huiyuezang** [comment]
我按照教程去查看token  但是值的一栏  只有https%3A%2F%2Fchat.openai.com 这个。。

**Comment by miu0007** [comment]
> 我按照教程去查看token 但是值的一栏 只有https%3A%2F%2Fchat.openai.com 这个。。

![2023-05-07 022619](https://user-images.githubusercontent.com/116816117/236638624-16fa0ba0-9d6c-4aa8-bb78-230461ba4b87.png)
