### ISSUE TITLE
同样报错，求佬们教

### ISSUE THREAD

**Issue by Minjie2003** [cjyaddone/ChatWaifu#20]
可以到You输入那一步，用的是中文输入转日文语音
Traceback (most recent call last):
  File "D:\ChatWaifu\ChatWaifuCN.py", line 342, in <module>
    resp = api.send_message(get_input())
  File "D:\Anoconda\envs\chatwaifu\lib\site-packages\pyChatGPT\pyChatGPT.py", line 460, in send_message
    conversation_id = matches.group()
AttributeError: 'NoneType' object has no attribute 'group'
试了几次都是这样

**Comment by MuBai-He** [comment]
版本问题，安装req里面的版本

**Comment by MuBai-He** [comment]
现在更新了确实出了点问题

**Comment by Minjie2003** [comment]
> 现在更新了确实出了点问题

噢，okk

**Comment by apollocrisis** [comment]
> 现在更新了确实出了点问题
大佬，现在有什么能够手动纠正的方法吗，对python不太懂（还有req里面的版本具体在哪，谢谢大佬了555）

**Comment by MuBai-He** [comment]
有点忙暂时帮不上了，考完也不知道ai发展成啥样了。我尽力

**Comment by apollocrisis** [comment]
> 有点忙暂时帮不上了，考完也不知道ai发展成啥样了。我尽力

祝考试顺利捏
