### ISSUE TITLE
输入问题后chrom浏览器闪退

### ISSUE THREAD

**Issue by MapleLeeLee** [cjyaddone/ChatWaifu#7]
大佬，问一个问题之后浏览器闪退，代码报错如下：
Traceback (most recent call last):
  File "E:\ChatWaifu-main\ChatWaifu.py", line 214, in <module>
    resp = api.send_message(get_input())
  File "D:\Software\anaconda3\lib\site-packages\pyChatGPT\pyChatGPT.py", line 444, in send_message
    response = self.driver.find_elements(*chatgpt_small_response)[-1]
IndexError: list index out of range

**Comment by MuBai-He** [comment]
这几天都有这个问题等大佬更新

**Comment by 954-Ivory** [comment]
```python
response = self.driver.find_elements(*chatgpt_small_response)[-1]
```

这里是因为直接 HTTP Error 1020 了。
应该是 openAI 锁代理了，我换了几个节点才可以。

**Comment by Aionstn** [comment]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ChatWaifu-main\ChatWaifuVoice.py", line 373, in <module>
    resp = api.send_message(voice_input_jpjp())
  File "D:\aconda\envs\chatWaifu\lib\site-packages\pyChatGPT\pyChatGPT.py", line 460, in send_message
    conversation_id = matches.group()
AttributeError: 'NoneType' object has no attribute 'group'

好像正则表达式挂了

**Comment by MuBai-He** [comment]
停止维护了，那个作者不做了。后期有可能会更新api版本
